name: Optimize Code

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JQ
        run: sudo apt-get install -y jq
      - name: Optimize Code
        run: |
          # Fetch source branch name
          
          pr_num=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          branch_name=$(gh pr view https://github.com/${GITHUB_REPOSITORY}/pull/${pr_num} --json baseRefName | jq -r '.baseRefName')
          echo "${pr_num}, ${branch_name}, ${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          # Check out new branch from the source branch
          git checkout -b optimized-${branch_name} ${branch_name}

          # Get a list of changed files in the pull request
          files=$(git diff --name-only origin/${branch_name}...${{ github.sha }})

          for file in ${files}; do
            if [[ $file == *.py ]]; then
              # Get the diff of each file
              diff=$(git diff origin/${branch_name}...${{ github.sha }} -- $file)

              # Call the API with the diff of the current file
              optimized_diff=$(curl -X POST -d "${diff}" https://dummyjson.com/products/add)

              # Apply the optimized diff
              echo "${optimized_diff}" | git apply
            fi
          done

          # Commit and push the changes
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -am "Optimized code"
          git push origin optimized-${branch_name}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}